meta_product_name: "Memo-me"
meta_title: "Memo-me - Remember those that you care about!"
meta_description: "Plan events. Create memories. Keep tabs on the kids around you, never forget special events again."
meta_image: "Memo-Me.png" # should exist in `app/assets/images/`
