meta_product_name: "Memo-me"
meta_title: "Memo-me - Product tagline"
meta_description: "Plan events. Create memories. Remember those that tou care about!"
meta_image: "Memo-Me.png" # should exist in `app/assets/images/`
